version: '2'
services:
    trafficanalyzer-app:
        image: trafficanalyzer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trafficanalyzer-mysql:3306/trafficanalyzer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trafficanalyzer-mysql:
        extends:
            file: mysql.yml
            service: trafficanalyzer-mysql
